[install]
production=true
peer=true
frozen=true
registry="https://registry.npmjs.org"

[install.cache]
dir=".bun/cache"
disable=false
enable-global=false

[test]
coverage=true
timeout=10000

[debug]
dump-js=false
profile=false

[runtime]
env-file=".env"
js-target="es2022"
preload=true

[optimization]
inline-css=true
minify-whitespace=true
tree-shake=true
